### PR TITLE
Enable hwyla integration

### PR DESCRIPTION
**Pull request by gucheen**

### CODE REVIEW

**Comment by CplPibald** [comment]
The HWYLA maven repository has moved.  See https://github.com/TehNut/HWYLA/issues/253

Changing `repositories.maven.url` in build.gradle allowed me to build.

    @@ -111,7 +111,7 @@ repositories {
         }
         maven { // HWYLA
             name = "HWYLA repo"
    -        url "http://tehnut.info/maven"
    +        url "http://maven.tehnut.info"
         }

**Comment by yourb3stnightmare** [comment]
I confirmed that these changes (with the url change) works with the latest Hywla (tested with Vahelsia 2).

**Comment by jorge-precich** [comment]
Really looking forward for this fix

**Comment by LordZardeck** [comment]
It's been a year since this pull request, and i'm having the same issue, discovered in Vahelsia 2. Any chance of this getting resolved?

**Comment by gucheen** [comment]
@LordZardeck StorageDrawers has re-provided hwyla(waila) support in 1.16 (currently the main branch), and you may switch to Vahelsia 3 which based on Minecraft 1.16.
This PR could be closed.

**Pull request closed without merging**
