### PR TITLE
Updated from 1.16.2 to 1.16.3 and updated to latest MCP and fixed all mappings as well as fixes Mekanism  Logistical Transporter not working with storage drawers

### LINKED ISSUE #811: 1.15.2 Mekanism integration / connections to drawers inconsistent
I first created this issue on the [Mekanism GitHub](https://github.com/mekanism/Mekanism/issues/5957). They have investigated, and believe the issue is on the Storage Drawer end.

There are some significant and unpredictable incompatibilities between Mekanism item manipulators (logistical transporters and logistical sorters), and Storage Drawers. Depending on the setup, Mekanism either doesn't recognize storage drawers as a possible item location, or doesn't recognize all of the slots within a drawer, or works properly. I recognize that the problem could be on either the Mekanism or Storage Drawers (or both!) side of things.

**Steps to reproduce:**
Start a fresh modded game with only Forge / Mekanism / Storage Drawers loaded.
Place a variety of Storage drawers, including compacting drawers, full drawers, and multi(2/4) drawers.

Try moving items from traditional storage (chest/hopper etc.) into storage drawers using either Mekanism logistical transporters or sorters + logistical transporters. The issue seems to be that Mekanism recognizes (n-1) storage drawer slots, where n is the total slots in that drawer. That means that a regular storage drawer (one full drawer, one item slot) isn't recognized as a valid target inventory, whether it is empty or already contains the item in question. Any of the other drawers that have more than one slot (like the 1x2 or 1x4 or half size 2 and 4 slot drawers) are recognized both as valid empty inventories in which to place something, as well as valid sources for pre-existing items, but the last slot is always ignored, and stays empty or (if already containing an item) untouched. Compacting drawers are a special case. Mekanism recognizes them as a single available empty slot, and will send a new item into an empty compacting drawer (both from logistical transporters and sorters). Thereafter, Mekanism will only recognize the "top" one or two inventories. An item that compacts into a block, but doesn't partition to a smaller 'nugget' will only be recognized in block form (e.g. the Drawer has two "inventories" and Mekanism only sees the first one). An item that compacts into a block, but also has a subform like a nugget will have the top /two/ inventories visible to Mekanism (e.g. the block/ingot, but not the nugget).

These limitations are partially mitigated by throwing Mekanism item logistics into a Storage Drawer controller block instead of directly into the drawers themselves. The controller seems to expose all the drawer slots to either sorters or transporters, and Mekanism will pull items and fill inventories for anything connected to the controller. In this scenario, the only part that isn't working is that Mekanism still uses the (n-1) rule when considering /empty/ inventory space. It will not push new items into a drawer that doesn't have one of its (n-1) slots available. Once an item is loaded into a drawer, though, even into a 'forbidden' slot, Mekanism will push more items into that inventory.

Version (make sure you are on the latest version before reporting):
**Forge: 31.1.18
**Storage Drawers: StorageDrawers-1.15.2-7.0.2
**Mekanism: Mekanism-1.15.2-9.9.15.408

Here is what they said in response:

> Finally got a chance to look into this some, and there is unfortunately nothing we can do on our end. I did some minor cleanup for the next alpha to our simulation checks [6880316](https://github.com/mekanism/Mekanism/commit/68803166ba949f0f9476c691f4a436ff8205bdda) but it does not solve this issue. I believe Storage Drawers is improperly implementing their item handler, as I tested with some debug messages, and the information the drawer returned was very conflicting logically.
> 
> For a basic oak drawer, their item handler returns that it has two slots. The first one is their [virtual slot](https://github.com/jaquadro/StorageDrawers/blob/1.15/src/main/java/com/jaquadro/minecraft/storagedrawers/capabilities/DrawerItemHandler.java#L165-L167), and their second is an internal slot.
> 
> The first [check](https://github.com/mekanism/Mekanism/blob/68803166ba949f0f9476c691f4a436ff8205bdda/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L56-L60) we make is to check the maximum amount of items allowed in a slot. (The JavaDocs for that method state: `The maximum stack size allowed in the slot.`)
> Storage Drawers, returns [MAX_INT](https://github.com/jaquadro/StorageDrawers/blob/1.15/src/main/java/com/jaquadro/minecraft/storagedrawers/capabilities/DrawerItemHandler.java#L147-L148) for their virtual slot, and from my debugging was returning zero for the internal slot. (Not sure if this is intended or not I don't feel like looking too deeply into their code).
> 
> This means due to them returning that only their virtual slot actually allows items into the slot that is the only slot we attempt to act upon. Next, we [check](https://github.com/mekanism/Mekanism/blob/68803166ba949f0f9476c691f4a436ff8205bdda/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L63-L65) to make sure the item is valid for the slot (it is). And then we [check](https://github.com/mekanism/Mekanism/blob/68803166ba949f0f9476c691f4a436ff8205bdda/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L72) how many items are currently in the destination. Because there is no item in the destination, we then [simulate](https://github.com/mekanism/Mekanism/blob/68803166ba949f0f9476c691f4a436ff8205bdda/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L81-L86) inserting into the slot, and if no items could be accepted into the slot we check the next slot.
> 
> The issue however is, that because the only slot StorageDrawers claims can fit more than zero items in is the virtual slot, BUT that any insertions into the virtual slot just [fail](https://github.com/jaquadro/StorageDrawers/blob/1.15/src/main/java/com/jaquadro/minecraft/storagedrawers/capabilities/DrawerItemHandler.java#L58-L62), we are unable to find a valid slot to insert items into.

### LINKED ISSUE #6637: [1.16.3] Issue with Storage Drawers
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
found a issue between Mekanism and storage drawers with the Logistical Transporter ands the storage drawers mod as they will not trans port items into the controller or the storage drawers but it will with the compacting drawers but i found a work around by doing this in my test environment https://github.com/raziel23x/StorageDrawers/tree/1.16 is the latest test build for the 1.16.3 version of storage drawers as its not released for 1.16.3 like projecte is it something on our end or is it on meks? I am looking for a second set of eyes to figure out who end is it really on
 to bypass the issue i used Cyclic item cable and a chest in the example screenshot i am using the diamond chest from iron chest mod
image

### Version (make sure you are on the latest version before reporting):
**Forge:**
34.1.23 
**Mekanism:** 
Mekanism-1.16.3-10.0.12.437
**Other relevant version:** 
StorageDrawers-1.16.3-8.2.0-SNAPSHOT
Cyclic-1.16.3-0.8.2
ironchest-1.16.3-11.2.6

### PR DESCRIPTION
**Pull request by raziel23x**
Updated from 1.16.2 to 1.16.3
Updated to latest MCP 20200916-1.16.2 and updated mapping
Updated dependecies to Latest 1.16.3 versions
Updated to latest Forge 34.1.22 which fixes tooltip issues and other misc forge related bugs see forge changelog for more details
Fixed malven related links to https
Updated HWYLA malven URL
Fixed Mekanism Logistical Transporter not working with storage drawers controller and 1x1 storage
close https://github.com/jaquadro/StorageDrawers/issues/811
close https://github.com/mekanism/Mekanism/issues/6637

### CODE REVIEW

**Review by raziel23x — COMMENTED** [review]
I have tested the changes and fixes in place here and have found no bugs so far and feel this is ready for merge and ready for use

**Review by raziel23x — COMMENTED** [review]
ready for merging

**Comment by LoaderB0T** [comment]
Strangely enough, I still have the issue with specific items: wither skeleton skulls and regular skeleton skulls. (I assume maybe all skulls). They do not get put in by the logistical transporters from Mekanism.

**Comment by jaquadro** [comment]
Possible those items have some sort of data tag on them?  Items need to be a 100% match and sometimes there's hidden data.

**Comment by LoaderB0T** [comment]
The item does not have any special tags (F3+G shows no additional data). I can put them manually inside the drawer, not with mekanism transporters... It does work with the cyclic item cables though. Might be a problem in the mekanism mod....

**Comment by devmattrick** [comment]
I'm also having issues with Mekanism pipes not being able to put items into the "top left" drawer when it has a void upgrade in it. Not sure if this is related or if I should make a separate issue.

**Pull request merged**
