### PR TITLE
Add a null check for players on BlockDrawers.isReplaceable

### PR DESCRIPTION
**Pull request by Laikulo**
This is to address #820

I assume the mod_version is semantic, but I can yank that out if desired.

### CODE REVIEW

**Comment by Hubry** [comment]
~~This doesn't address all the cases - for example, Botania (Rannuncarpus flower) and Quark (Dispensers place blocks module) crash in onBlockPlacedBy:~~
Whoops, didnt see the other PR

**Comment by Laikulo** [comment]
@hubry That is already covered by PR #786

**Comment by Hubry** [comment]
Whoops, I didn't see that. I only saw this issue this PR links and skipped going through others, thinking it's just this PR. The issues are pretty closely related anyways.

**Comment by Laikulo** [comment]
Thanks for bringing that to my attention anyways, I'm currently operating a 1.15.2 private server with the version from my fork, which does not have the other tweak. If the pair of them don't get merged before I spin the pack again, I'll grab that one into a branch.

**Comment by Laikulo** [comment]
@jaquadro Would you like this split for 1.16, or rebased there?

**Pull request closed without merging**
