### PR TITLE
Add Immersive Engineering Treated Wood drawers.

### PR DESCRIPTION
**Pull request by codewarrior0**
This patch to StorageDrawers-Misc adds all five drawer types and trim made from [Immersive Engineering](http://www.curse.com/mc-mods/minecraft/231951-immersive-engineering)'s Treated Wood planks.

image

The TextureBuilder tool came in really handy for this! The textures could use a bit more touching up, but at least all of the wiring is done.

(BTW, what do you do to build the packs? `gradle build` didn't work until I added some dependency info to the pack's build scripts.)

### CODE REVIEW

**Comment by jaquadro** [comment]
What were your changes to the build script?  Gradle has been a persistently weak area for me.  Given that the packs are nested inside the project they depend on, I didn't know how to get them to resolve the dep.  I've just been copying a build of Storage Drawers into their lib folders.

Thanks for the patch.  The base textures look pretty decent to me, considering that the source planks look like a really difficult set to work with.

**Comment by codewarrior0** [comment]
The planks are supposed to have a "sheen" from being treated with heavy oil, and I wanted to show that on the drawers too, but it was getting late and I was starting to fall asleep. Maybe someday I'll spend some more time on them. 

I'm about to send another PR with my build script changes.

**Comment by codewarrior0** [comment]
I made a wiki page that covers what I learned while adding these drawers. Comments/corrections are more than welcome!

https://github.com/jaquadro/StorageDrawers/wiki/How-to-add-a-new-drawer-style

**Comment by jaquadro** [comment]
Thanks for the wiki contribs.  The misc pack could have certainly been designed in a more friendly manner.

There's some gotchas still present, namely the banks can only hold 16 definitions (a direct map to block meta), so anyone adding enough blocks to overflow the bank will need to put some blocks in the other one, or make a new bank (which also requires another entry in the main mod file).

**Pull request merged**
