### PR TITLE
Update to Minecraft 1.17

### PR DESCRIPTION
**Pull request by rrehbein**
Update to support Minecraft 1.17

This also replaces [HWYLA](https://www.curseforge.com/minecraft/mc-mods/hwyla) integration with [Jade.](https://www.curseforge.com/minecraft/mc-mods/jade)

This shouldn't be merged as is. I am not sure how to open a PR to a branch that doesn't exist yet.

### CODE REVIEW

**Comment by rrehbein** [comment]
This appears to add a rendering bug to the compacting drawer when it is only two items. eg: sand or bricks. It doesn't appear to trigger for three items. eg: iron ingot.

Steps:

1. Set up a compacting draw with sand/sandstone
2. Open the drawer screen gui
3. Close the gui

Expected:
- Item to stay visible

Actual:
- Item disappears till a block update happens, such as adding or removing an item.

Edit: Fixed with 5fbd673

**Comment by rrehbein** [comment]
There is a remaining "to do" for the following line. There doesn't appear to be a direct replacement in 1.17. I also wasn't sure of the steps to replicate the issue missing the line creates to verify it is actually still needed.

```
((ServerPlayer) player).refreshContainer(player.inventoryMenu)
```

**Comment by jaquadro** [comment]
Hi,

I was about to settle into the slog of the 1.17 migration, but glanced through my activity feed and saw this.  I'm about to take a closer look at this, but wanted to mention I'm looking for permanent help with maintaining this mod.  Feel free to reach out to me on discord if you'd like to chat more.

**Comment by jaquadro** [comment]
This is fantastic, not seeing any major issues with the basics or loading up my standard test world.  I'm going to publish the beta for 1.17, see if anything major turns up.

Thank you so much for contributing this.

**Pull request merged**
