### PR TITLE
Add "one stack" upgrade.

### PR DESCRIPTION
**Pull request by uecasm**
This adds an upgrade item (crafted like a storage upgrade but with flint in the corners) that reduces the base capacity of any drawer to one stack; it can still be increased further via storage upgrades.

There's no special indication in WAILA that the upgrade is installed, other than the capacity reducing.  I thought about adding something, but it didn't really seem necessary.

It should be all "safe" -- it won't accept more than one such upgrade and won't accept the upgrade if any drawer already contains more than 1 stack of items (or whatever the capacity would be reduced to. if storage upgrades are already installed).  Though I've only tested adding/removing upgrades via player interaction, I don't know if there's some other way to do it that might bypass the check.

I did briefly experiment with having incremental downgrades, or having it be another variant of the Storage Upgrade, but they both get messy very quickly.  This seemed like a better solution.

Note that this is my first attempt to write any Minecraft mod code, so I might have missed something.  Seems to all work ok in my testing, though.

One thing that did puzzle me a little in the implementation: `InventoryUpgrade.isItemValidForSlot` is not called when the player tries to drop an upgrade into the slot using the drawer GUI.  I added a check in there anyway but I'm not sure what it affects.  The thing that actually blocked player insertion was `SlotUpgrade.isItemValid`.

This might be a pre-existing bug, given that I seem to be able to put cobble in the upgrade slots (even in the released version, so it's not my changes).  Perhaps the other code needs to be moved?  Or the latter needs to call the former?

### CODE REVIEW

**Comment by uecasm** [comment]
Looks like the docs say that `isItemValidForSlot` is for automation and `isItemValid` is for player GUI.  So probably both ought to have the check to only accept upgrades (probably by making `isItemValid` call `isItemValidForSlot`, or both calling a common helper in `InventoryUpgrade`).  That's unrelated to this PR, though.

**Comment by samtrion** [comment]
Hi, ich glaube dein Vorgehen mit einem "OneStack Downgrade" ist zu rabiat.
Warum wird die bestehende Methodik der Upgrades nicht umgekehrt und es werden auch Downgrades zur Verfügung gestellt.

Als Beispiel:
Flint, Multiplikator -2
Clay, Multiplikator -4
String, Multiplikator -8

**Comment by uecasm** [comment]
As I said in the original comment, I did try something like that first, but the implementation gets quite ugly.

I think the most likely use for storage reduction would be to store a single stack anyway, making this the most useful upgrade by itself.  (Reducing storage only really makes sense when you're using drawers in combination with automation and thus you want to limit the number of items that can be autocrafted/buffered/stored.)

But you're not limited to a single stack either -- you can put a Storage Downgrade and a Storage Upgrade x2 in a drawer block to get 2 stacks per individual sub-drawer, for example.  (Larger upgrades work too, of course.)  And you can put the same item in two sub-drawers of a 1x2 or 2x2 drawer to get double the storage of that, too.

**Comment by jaquadro** [comment]
Sorry I haven't commented on this yet.  I've been meaning to pull it down for a more in-depth review, but I've been distracted actually playing Minecraft for the last few weeks.

**Comment by uecasm** [comment]
Actually playing the game?  The horror! :laughing:

**Comment by jaquadro** [comment]
Okay, I finally sat down to work on the mod for a bit.  Everything looked good, and rebasing the multiplier on the one stack is actually a pretty elegant alternative to the fractional reducers.  I think the fractional reducers could work in 1.8+, but they were definitely not viable at all in 1.7.10.

I did a little housekeeping around the upgrade item classes while I was in there, and fixed the "put cobble in upgrade slots" bug.

This was a really old feature request that has come up again and again and it's actually embarrassing that I haven't done anything with it yet, so thanks for contributing your solution.  I'll put out a new release this weekend.

**Pull request merged**
