### PR TITLE
Add: Japanese localization

### PR DESCRIPTION
**Pull request by sharpedmimishee**
## What I added
- Japanese localization(ja_jp)

I added Japanese translation to ja_jp.json based on en_us.json. Instead of translating all at once using a translation site, I checked the translation keys one by one. Therefore, the translation result is slightly different from that of https://translate.google.com/.

### CODE REVIEW

**Comment by jaquadro** [comment]
Hey, thanks for providing a translation.  I'm trying to shift to managing translations on Crowdin.  If you're interested in contributing translations there, I believe you can start by uploading this file to add most of the strings.  If not, I can upload it on your behalf.  There's also a few more strings that have been added to the language file since this PR.

https://crowdin.com/project/storage-drawers

I'll merge this as-is for now.

**Comment by sharpedmimishee** [comment]
> Hey, thanks for providing a translation. I'm trying to shift to managing translations on Crowdin. If you're interested in contributing translations there, I believe you can start by uploading this file to add most of the strings. If not, I can upload it on your behalf. There's also a few more strings that have been added to the language file since this PR.
> 
> https://crowdin.com/project/storage-drawers
> 
> I'll merge this as-is for now.

Thank you for merging.
I'm very interested in translating your mod, but I must be over 18 to use Crowdin's service. Therefore, I can't use Crowdin to translate it. (I would like to translate it though.)

**Comment by sharpedmimishee** [comment]
If you don't mind, I would like to continue translating using the PR function on github. What do you think?

Edit: I fixed my typo #1165

**Comment by jaquadro** [comment]
In this case it's okay to use PRs.  I'll add them to Crowdin as needed.  It's also possible other translators will make revisions there as well.

**Pull request merged**
